version: '3'

services:
  db_main:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_prisma
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '9090:3306'

  db_slave:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_prisma
      - MYSQL_MASTER_HOST=db_main
      - MYSQL_MASTER_USER=root
      - MYSQL_MASTER_PASSWORD=root
      - MYSQL_MASTER_PORT=3306
    volumes:
      - ./mysql_slave:/var/lib/mysql
    depends_on:
      - db_main
