version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_prisma
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_prisma
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks: 
      - ecommerce

networks:
  ecommerce:
    driver: bridge
